name: clride1
channels:
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - python=3.7.3
  # https://www.anaconda.com/utilizing-the-new-compilers-in-anaconda-distribution-5/
  - c-compiler=1.0.4
  - gxx_linux-64
  - cmake=3.14.0
  - qt=5.12.5  # conda-forge does not have 5.13.2 available
  - pip
  - pip:
    - gym3==0.3.3
    - appdirs==1.4.4
    - certifi==2019.11.28
    - cffi==1.13.2
    - cfgv==3.1.0
    - cloudpickle==1.2.2
    - distlib==0.3.0
    - filelock==3.0.12
    - future==0.18.2
    - gitdb2==2.0.6
    - GitPython==3.0.5
    - gym==0.15.4
    - gym-super-mario-bros==7.3.0
    - identify==1.4.19
    - importlib-metadata==1.6.1
    - importlib-resources==2.0.0
    - nes-py==8.1.1
    - nodeenv==1.4.0
    - numpy==1.17.4
    - olefile==0.46
    - opencv-python==4.1.2.30
    - Pillow==6.2.1
    - pre-commit==2.5.1
    - pycparser==2.19
    - pyglet==1.3.2
    - PyQt5==5.13.2
    - PyQt5-sip==12.7.0
    - PyYAML==5.3.1
    - scipy==1.3.3
    - six==1.13.0
    - smmap2==2.0.5
    - toml==0.10.1
    - torch==1.1.0
    - torchvision==0.3.0
    - tqdm==4.40.2
    - virtualenv==20.0.21
    - zipp==3.1.0
    - gym-minigrid==1.0.1
    - procgen==0.10.4

